baseURL = "https://oli.fyi/"
languageCode = "de-ch"
title = "Oliver Kamer"

theme = "business-card"

defaultContentLanguage = "de-ch"

enableRobotsTXT = true

environment = "production"
removePathAccents=true

disableKinds = ["taxonomy", "taxonomyTerm"]



[imaging]
	resampleFilter = "lanczos"
	quality = 85

[languages]
	[languages.de-ch]
    languageName = "Deutsch"
    weight = 1
	[languages.en]
    languageName = "English"
		weight = 2

[mediaTypes]
	[mediaTypes."text/vcard"]
		suffixes = ["vcf"]

[outputFormats]
  [outputFormats.vcf]
    baseName = "contact"
    path = "vcard"
    isPlainText = true
    mediaType = "text/vcard"
    protocol = "https://"